require("avery.settings")
require("avery.remap")

require("avery.plugins.tree")
require("avery.plugins.catppuccin")
require("avery.plugins.winbar")
require("avery.plugins.feline")
require("avery.plugins.telescope")
require("avery.plugins.treesitter")
require("avery.plugins.undotree")
require("avery.plugins.lsp")