#!/usr/bin/env bash

exit_script() {
    echo -e "\r     "
    echo -e "\r${Red}Failed to rebuild system!${Color_Off}"
    echo
    echo -e "Errors:"
    echo -e "\t${Red}Terminated by user."
    trap - SIGINT SIGTERM # clear the trap
    exit
}

trap exit_script SIGINT SIGTERM

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

DOTFILES_LOCATION=~/code/projects/current/dotfiles
OLD_LOCATION=$(pwd)

cd $DOTFILES_LOCATION

echo
echo -e "[1/2] ${Blue}editing system configuration...${Color_Off}"

nvim . # Open the editor

git add . 2>&1 >/dev/null
git status

echo -n "Enter commit name: "
read commit

git commit -m "$commit" 2>&1 >/dev/null

echo -e "[2/2] ${Blue}rebuilding system...${Color_Off}"
echo
if result=$(sudo nixos-rebuild switch --flake .#$(hostname) --option eval-cache false 2>&1); then
    #git push
    echo -e "${Green}System Rebuilt!${Color_Off}"
else
    echo -e "${Red}Failed to rebuild system!${Color_Off}"
fi

result=$(echo -e "$result" | sed 's/\x1b\[[0-9;]*m//g')

warnings=$(echo -e "$result" | grep "warning")
errors=$(echo -e "$result" | grep -e "error" -e "- In" | grep -Ev "^error:$" | sed -e "s/- In \`\/nix\/store\/.*-source\/\(.*\)'/ - \1/g")
echo
if [ ! -z "$warnings" ]; then
    echo -e "Warnings:"
    echo -e "$warnings" | while read line; do
        echo -e "\t${Yellow}${line}${Color_Off}"
    done
fi
if [ ! -z "$errors" ]; then
    echo -e "Errors:"
    echo -e "$errors" | while read line; do
        echo -e "\t${Red}${line}${Color_Off}"
    done
fi

tmpfile=$(mktemp -t rebuild_XXXXXX)

echo
echo "For full log, run 'cat $(realpath "$tmpfile")'"

echo -e "$result" > $tmpfile

cd $OLD_LOCATION
