{pkgs, lib}: {
    services.issue = {
        enable = true;
        items = [
            "Where are we?"
            "What the hell is going on?"
            "The dust has only just begun to form"
            "Sinking, feeling"
            "This can't be happening"
            "When busy streets"
            "Hide and seek"
            "They were here first"
            "Mm, what'd you say?"
            "Mm, that you only meant well"
            "Well of course you did"
            "Mm, that it's all for the best"
            "Mm, that it's just what we need"
            "Ransom notes keep falling out your mouth"
            "Mid-sweet talk, newspaper word cutouts"
            "Speak no feeling, no, I don't believe you"
            "You don't care a bit, you don't care a bit"
            "Yahaha! You found me!"
            "Its dangerous to go alone! Take this."
            "You've met with a terrible fate, haven't you?"
            "It’s a little story I like to call The Legend of Groose!"
            "\"I call it the Groosenator\" -Groose"
            "Hey! Listen!"
            "Tingle, Tingle! Kooloo-Limpah!"
            "Dah-na-na-na-naaaaaaaa!"
            "The blood moon rises once again..."
            "Master, the batteries in your Wii Remote are nearly depleted"
            "Despite everything, it's still you"
            "You should be smiling, too. Aren't you excited? Aren't you happy? You're going to be free."
            "It fill you with determination"
            "If you'll be my bodyguard"
            "I can be your long lost pal"
            "And Betty, when you call me, you can call me Al"
            "Frogs are people too"
            "So be it. Let your will be done."
            "What meaning can we find in a world that has no purpose?"
            "In the beginning were the words..."
            "You were always meant to defy me. That was the final trial."
            "Two plus two is- f- f- f-... ten. In base 4! I'm Fine!"
            "How are you? Because I'm a potato."
            "well... this is the part where he kills us"
            "Hello, this is the part where i kill you"
            "When life gives you lemons, don't make lemonade!"
            "I don't want your damn lemons; what am I supposed to do with these?"
            "Make life rue the day it thought it could give Cave Johnson lemons!"
            "I'm gonna get my engineers to invent a combustible lemon that burns your house down!"
            "We do what we must because we can."
            "I punched those numbers into my calculator it makes a happy face."
            "Are you still there?"
            "Target lost."
            "Make it so, Number One."
            "Engage."
            "Tea. Earl Grey. Hot."
        ];
    };
}
